# Generated by Django 4.2.11 on 2024-04-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='titile',
            new_name='title',
        ),
    ]
